### ISSUE TITLE
a little confusion

### ISSUE THREAD

**Issue by iowrite** [vuquangtrong/STM32-Tutorials#1]
hi , i am watching you website article:https://www.codeinsideout.com/blog/stm32/semihosting/
and i maybe find some place incorrect in it.
2.3. Debugger option: the "SemiHosting" should be semihosting
3. Debug with SemiHosting: in the article, you give a note that useing fopen in linux,  i think the file path parameter shoud be absolute path.
thank you for you article, it gives me a lot help : )

**Comment by vuquangtrong** [comment]
hi @hellowoad 

Thanks for visiting my page, and pointing my mistakes ( I though it was the replace function in editor).

About the file path, here is the original guide from ARM (in [here](https://developer.arm.com/documentation/100863/0300/Semihosting-operations/SYS-OPEN--0x01-?lang=en)):
> When using `fopen()`, the file path is specified either as relative to the current directory of the host process (e.g. `openocd.exe`), or absolute, using the path conventions of the host operating system.

However, the actual behavior may vary, depending on the implementation of the debugger. 

I updated the page. When I have more free time, I will continue adding more posts.
